server:
  port: 8100
spring:
  application:
    name: pro-zuul
#zuul:
  #routes:
    #user:
      #path: /user/**
      #serviceId: pro-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/